/// The whole of one Festival Quest adventure, as data.
///
/// An adventure is content, not code: three locations, four characters, a
/// market, a mystery, a courtyard to prepare and two endings. The engine can
/// play any adventure that satisfies [AdventureValidator], whether it was
/// written by hand (`kPongalAdventure`) or generated by Gemini and checked
/// before anybody saw it.
///
/// Everything here serialises, because a generated adventure is saved to the
/// device and replayed offline.
library;

import 'dart:convert';

import 'package:flutter/material.dart';

import 'adventure_icons.dart';
import 'requirement.dart';

/// Where an adventure came from. Shown to the player, because "made for you
/// just now" and "the one that ships with the app" are different things and
/// they should know which they are playing.
enum AdventureSource {
  bundled('The adventure that comes with MindPal'),
  generated('Made for you by MindPal');

  const AdventureSource(this.label);
  final String label;

  static AdventureSource fromName(String? name) => AdventureSource.values
      .firstWhere((value) => value.name == name, orElse: () => bundled);
}

/// What an interactive point on a scene is for.
enum HotspotKind {
  /// Someone to talk to.
  character,

  /// Something to look at, and perhaps pick up.
  object,

  /// A way to another location.
  exit,

  /// Opens the market stalls.
  market,

  /// Opens the "where was it?" screen of the mystery.
  accuse,

  /// Opens the courtyard preparation.
  prepare,
}

/// A tappable point in a scene.
class Hotspot {
  const Hotspot({
    required this.id,
    required this.label,
    required this.kind,
    required this.x,
    required this.y,
    this.targetId,
    this.icon = Icons.help_outline_rounded,
    this.color = const Color(0xFF00695C),
    this.visibleWhen = Requirement.none,
    this.inspectText,
    this.onInspect = Effect.none,
    this.repeatable = true,
  });

  final String id;

  /// Always drawn under the picture. Nothing in this game is a guess-the-icon
  /// puzzle.
  final String label;

  final HotspotKind kind;

  /// Position within the scene, 0..1 of width and height. Fractions rather
  /// than pixels so one scene lays out on any screen without a second design.
  final double x;
  final double y;

  /// The character, item or location this points at, depending on [kind].
  final String? targetId;

  final IconData icon;
  final Color color;

  /// Hidden until this holds. A hotspot the player cannot yet use is absent
  /// rather than greyed out — a dead control invites tapping.
  final Requirement visibleWhen;

  /// Shown when an object is tapped, before its effect applies.
  final String? inspectText;

  final Effect onInspect;

  /// False for a one-shot: once its effect has run it disappears. Used for
  /// objects that are picked up.
  final bool repeatable;

  Map<String, dynamic> toMap() => {
    'id': id,
    'label': label,
    'kind': kind.name,
    'x': x,
    'y': y,
    if (targetId != null) 'targetId': targetId,
    'icon': adventureIconName(icon),
    'color': color.toARGB32(),
    if (!visibleWhen.isAlwaysMet) 'visibleWhen': visibleWhen.toMap(),
    if (inspectText != null) 'inspectText': inspectText,
    if (!onInspect.isEmpty) 'onInspect': onInspect.toMap(),
    'repeatable': repeatable,
  };

  factory Hotspot.fromMap(Map<String, dynamic> map) => Hotspot(
    id: map['id'] as String? ?? '',
    label: map['label'] as String? ?? '',
    kind: HotspotKind.values.firstWhere(
      (value) => value.name == map['kind'],
      orElse: () => HotspotKind.object,
    ),
    x: (map['x'] as num?)?.toDouble() ?? 0.5,
    y: (map['y'] as num?)?.toDouble() ?? 0.5,
    targetId: map['targetId'] as String?,
    icon: adventureIcon(map['icon'] as String?),
    color: Color((map['color'] as num?)?.toInt() ?? 0xFF00695C),
    visibleWhen: Requirement.fromMap(
      map['visibleWhen'] as Map<String, dynamic>?,
    ),
    inspectText: map['inspectText'] as String?,
    onInspect: Effect.fromMap(map['onInspect'] as Map<String, dynamic>?),
    repeatable: map['repeatable'] as bool? ?? true,
  );
}

/// One of the three places the adventure happens in.
class AdventureLocation {
  const AdventureLocation({
    required this.id,
    required this.name,
    required this.description,
    required this.hotspots,
    this.skyColor = const Color(0xFFBBDEFB),
    this.groundColor = const Color(0xFFCDBBA0),
    this.visitFlag,
  });

  final String id;
  final String name;

  /// One or two sentences setting the scene, read aloud where a voice exists.
  final String description;

  final List<Hotspot> hotspots;

  /// The scene is drawn, not photographed — see the note in AdventureScene.
  /// These two colours are its sky and ground.
  final Color skyColor;
  final Color groundColor;

  /// Set the first time the player arrives. Lets dialogue react to where
  /// somebody has already been.
  final String? visitFlag;

  Map<String, dynamic> toMap() => {
    'id': id,
    'name': name,
    'description': description,
    'skyColor': skyColor.toARGB32(),
    'groundColor': groundColor.toARGB32(),
    if (visitFlag != null) 'visitFlag': visitFlag,
    'hotspots': hotspots.map((spot) => spot.toMap()).toList(),
  };

  factory AdventureLocation.fromMap(Map<String, dynamic> map) =>
      AdventureLocation(
        id: map['id'] as String? ?? '',
        name: map['name'] as String? ?? '',
        description: map['description'] as String? ?? '',
        skyColor: Color((map['skyColor'] as num?)?.toInt() ?? 0xFFBBDEFB),
        groundColor: Color((map['groundColor'] as num?)?.toInt() ?? 0xFFCDBBA0),
        visitFlag: map['visitFlag'] as String?,
        hotspots: [
          for (final raw in (map['hotspots'] as List? ?? const []))
            if (raw is Map<String, dynamic>) Hotspot.fromMap(raw),
        ],
      );
}

/// One thing the player can say, and what it does.
class DialogueChoice {
  const DialogueChoice({
    required this.id,
    required this.text,
    this.requires = Requirement.none,
    this.effect = Effect.none,
    this.reply,
    this.goTo,
    this.isDecision = false,
  });

  final String id;

  /// What the player says. Written as the player's own words, not as a menu
  /// label: "I'll fetch it for you", not "Accept quest".
  final String text;

  final Requirement requires;
  final Effect effect;

  /// What the character says back, before moving on.
  final String? reply;

  /// The node to continue to. Null ends the conversation.
  final String? goTo;

  /// Marks a choice that shapes the ending. Recorded in the adventure summary
  /// so the player can see what they decided, and why they got the ending
  /// they got.
  final bool isDecision;

  Map<String, dynamic> toMap() => {
    'id': id,
    'text': text,
    if (!requires.isAlwaysMet) 'requires': requires.toMap(),
    if (!effect.isEmpty) 'effect': effect.toMap(),
    if (reply != null) 'reply': reply,
    if (goTo != null) 'goTo': goTo,
    if (isDecision) 'isDecision': true,
  };

  factory DialogueChoice.fromMap(Map<String, dynamic> map) => DialogueChoice(
    id: map['id'] as String? ?? '',
    text: map['text'] as String? ?? '',
    requires: Requirement.fromMap(map['requires'] as Map<String, dynamic>?),
    effect: Effect.fromMap(map['effect'] as Map<String, dynamic>?),
    reply: map['reply'] as String?,
    goTo: map['goTo'] as String?,
    isDecision: map['isDecision'] as bool? ?? false,
  );
}

/// One thing a character says, with the replies available.
class DialogueNode {
  const DialogueNode({
    required this.id,
    required this.lines,
    this.choices = const [],
    this.requires = Requirement.none,
    this.onEnter = Effect.none,
    this.isKeyMoment = false,
  });

  final String id;

  /// Spoken one panel at a time, so a long speech never becomes a wall.
  final List<String> lines;

  final List<DialogueChoice> choices;

  /// Which node a character opens with is decided by these: the FIRST node in
  /// the character's list whose requirement is met. So the list runs from most
  /// specific to most general, and the last one should always be reachable —
  /// the validator checks that a character can always say something.
  final Requirement requires;

  final Effect onEnter;

  /// Kept in the journal so the player can read it again. A conversation that
  /// carried a request or a clue must never be a thing you can only hear once.
  final bool isKeyMoment;

  Map<String, dynamic> toMap() => {
    'id': id,
    'lines': lines,
    if (choices.isNotEmpty)
      'choices': choices.map((choice) => choice.toMap()).toList(),
    if (!requires.isAlwaysMet) 'requires': requires.toMap(),
    if (!onEnter.isEmpty) 'onEnter': onEnter.toMap(),
    if (isKeyMoment) 'isKeyMoment': true,
  };

  factory DialogueNode.fromMap(Map<String, dynamic> map) => DialogueNode(
    id: map['id'] as String? ?? '',
    lines: [
      for (final line in (map['lines'] as List? ?? const []))
        if (line is String) line,
    ],
    choices: [
      for (final raw in (map['choices'] as List? ?? const []))
        if (raw is Map<String, dynamic>) DialogueChoice.fromMap(raw),
    ],
    requires: Requirement.fromMap(map['requires'] as Map<String, dynamic>?),
    onEnter: Effect.fromMap(map['onEnter'] as Map<String, dynamic>?),
    isKeyMoment: map['isKeyMoment'] as bool? ?? false,
  );
}

/// Somebody to talk to.
class AdventureCharacter {
  const AdventureCharacter({
    required this.id,
    required this.name,
    required this.role,
    required this.locationId,
    required this.nodes,
    this.icon = Icons.person_rounded,
    this.color = const Color(0xFF00695C),
  });

  final String id;
  final String name;

  /// "The potter", "Ammal's grandson". Shown under the name, so a player who
  /// has forgotten who somebody is does not have to remember.
  final String role;

  final String locationId;
  final List<DialogueNode> nodes;
  final IconData icon;
  final Color color;

  Map<String, dynamic> toMap() => {
    'id': id,
    'name': name,
    'role': role,
    'locationId': locationId,
    'icon': adventureIconName(icon),
    'color': color.toARGB32(),
    'nodes': nodes.map((node) => node.toMap()).toList(),
  };

  factory AdventureCharacter.fromMap(Map<String, dynamic> map) =>
      AdventureCharacter(
        id: map['id'] as String? ?? '',
        name: map['name'] as String? ?? '',
        role: map['role'] as String? ?? '',
        locationId: map['locationId'] as String? ?? '',
        icon: adventureIcon(map['icon'] as String?),
        color: Color((map['color'] as num?)?.toInt() ?? 0xFF00695C),
        nodes: [
          for (final raw in (map['nodes'] as List? ?? const []))
            if (raw is Map<String, dynamic>) DialogueNode.fromMap(raw),
        ],
      );
}

/// Something that can be carried, bought or given.
class AdventureItem {
  const AdventureItem({
    required this.id,
    required this.name,
    required this.description,
    this.icon = Icons.inventory_2_rounded,
    this.color = const Color(0xFF8D4004),
    this.price = 0,
  });

  final String id;
  final String name;
  final String description;
  final IconData icon;
  final Color color;

  /// In coins. Zero for anything that is not sold.
  final int price;

  Map<String, dynamic> toMap() => {
    'id': id,
    'name': name,
    'description': description,
    'icon': adventureIconName(icon),
    'color': color.toARGB32(),
    'price': price,
  };

  factory AdventureItem.fromMap(Map<String, dynamic> map) => AdventureItem(
    id: map['id'] as String? ?? '',
    name: map['name'] as String? ?? '',
    description: map['description'] as String? ?? '',
    icon: adventureIcon(map['icon'] as String?),
    color: Color((map['color'] as num?)?.toInt() ?? 0xFF8D4004),
    price: (map['price'] as num?)?.toInt() ?? 0,
  );
}

/// One seller in the market.
class MarketStall {
  const MarketStall({
    required this.id,
    required this.name,
    required this.keeperLine,
    required this.itemIds,
    this.soldOutItemIds = const {},
    this.icon = Icons.storefront_rounded,
    this.color = const Color(0xFF8D4004),
  });

  final String id;
  final String name;

  /// What the stallholder says when you walk up.
  final String keeperLine;

  final List<String> itemIds;

  /// Items this stall lists but has run out of. Exactly the mechanism behind
  /// "handle one unavailable item": the player sees it, cannot buy it, and has
  /// to ask about an alternative.
  final Set<String> soldOutItemIds;

  final IconData icon;
  final Color color;

  Map<String, dynamic> toMap() => {
    'id': id,
    'name': name,
    'keeperLine': keeperLine,
    'itemIds': itemIds,
    if (soldOutItemIds.isNotEmpty) 'soldOutItemIds': soldOutItemIds.toList(),
    'icon': adventureIconName(icon),
    'color': color.toARGB32(),
  };

  factory MarketStall.fromMap(Map<String, dynamic> map) => MarketStall(
    id: map['id'] as String? ?? '',
    name: map['name'] as String? ?? '',
    keeperLine: map['keeperLine'] as String? ?? '',
    itemIds: [
      for (final id in (map['itemIds'] as List? ?? const []))
        if (id is String) id,
    ],
    soldOutItemIds: {
      for (final id in (map['soldOutItemIds'] as List? ?? const []))
        if (id is String) id,
    },
    icon: adventureIcon(map['icon'] as String?),
    color: Color((map['color'] as num?)?.toInt() ?? 0xFF8D4004),
  );
}

/// One thing on the shopping list.
class MarketRequest {
  const MarketRequest({
    required this.id,
    required this.label,
    required this.acceptedItemIds,
  });

  final String id;

  /// What was asked for, in the character's words: "something sweet for the
  /// pot". Deliberately not an item id — the player is told what is NEEDED and
  /// works out what satisfies it.
  final String label;

  /// Every item that satisfies this request. More than one wherever it makes
  /// sense, so there is rarely a single correct basket.
  final List<String> acceptedItemIds;

  bool isSatisfiedBy(Set<String> owned) =>
      acceptedItemIds.any(owned.contains);

  Map<String, dynamic> toMap() => {
    'id': id,
    'label': label,
    'acceptedItemIds': acceptedItemIds,
  };

  factory MarketRequest.fromMap(Map<String, dynamic> map) => MarketRequest(
    id: map['id'] as String? ?? '',
    label: map['label'] as String? ?? '',
    acceptedItemIds: [
      for (final id in (map['acceptedItemIds'] as List? ?? const []))
        if (id is String) id,
    ],
  );
}

/// The shopping part of the adventure.
class MarketConfig {
  const MarketConfig({
    required this.startingCoins,
    required this.stalls,
    required this.requests,
    required this.completedFlag,
  });

  /// The purse. Every price and every total is an integer, so the budget never
  /// depends on a rounding rule nobody can see.
  final int startingCoins;

  final List<MarketStall> stalls;
  final List<MarketRequest> requests;

  /// Set once every request is satisfied.
  final String completedFlag;

  Map<String, dynamic> toMap() => {
    'startingCoins': startingCoins,
    'completedFlag': completedFlag,
    'stalls': stalls.map((stall) => stall.toMap()).toList(),
    'requests': requests.map((request) => request.toMap()).toList(),
  };

  factory MarketConfig.fromMap(Map<String, dynamic> map) => MarketConfig(
    startingCoins: (map['startingCoins'] as num?)?.toInt() ?? 0,
    completedFlag: map['completedFlag'] as String? ?? 'market_done',
    stalls: [
      for (final raw in (map['stalls'] as List? ?? const []))
        if (raw is Map<String, dynamic>) MarketStall.fromMap(raw),
    ],
    requests: [
      for (final raw in (map['requests'] as List? ?? const []))
        if (raw is Map<String, dynamic>) MarketRequest.fromMap(raw),
    ],
  );
}

/// One thing the player has noticed.
class Clue {
  const Clue({
    required this.id,
    required this.text,
    required this.source,
    this.icon = Icons.search_rounded,
  });

  final String id;

  /// The clue itself, as a plain observation: "The rope on the west post is
  /// frayed, as if something heavy hung from it."
  final String text;

  /// Where it came from, for the journal: "Told by Kannan".
  final String source;

  final IconData icon;

  Map<String, dynamic> toMap() => {
    'id': id,
    'text': text,
    'source': source,
    'icon': adventureIconName(icon),
  };

  factory Clue.fromMap(Map<String, dynamic> map) => Clue(
    id: map['id'] as String? ?? '',
    text: map['text'] as String? ?? '',
    source: map['source'] as String? ?? '',
    icon: adventureIcon(map['icon'] as String?),
  );
}

/// The mystery of the missing decoration.
class MysteryConfig {
  const MysteryConfig({
    required this.question,
    required this.clues,
    required this.candidateLocationIds,
    required this.solutionLocationId,
    required this.supportingClueIds,
    required this.revealText,
    required this.wrongLocationHint,
    required this.wrongCluesHint,
    required this.solvedFlag,
    required this.decorationItemId,
  });

  /// "Where did the kolam stencil go?"
  final String question;

  /// Exactly three, by the rules of this game.
  final List<Clue> clues;

  /// The places the player may name. Always more than one, or there is no
  /// question to answer.
  final List<String> candidateLocationIds;

  final String solutionLocationId;

  /// The clues that actually justify the answer. The player must pick these to
  /// explain their conclusion — naming the right place by luck is not solving
  /// a mystery.
  final Set<String> supportingClueIds;

  final String revealText;

  /// Shown for a wrong place, and for the right place with the wrong reasons.
  /// Both are nudges, and neither ends the adventure.
  final String wrongLocationHint;
  final String wrongCluesHint;

  final String solvedFlag;

  /// What the player recovers by solving it.
  final String decorationItemId;

  Map<String, dynamic> toMap() => {
    'question': question,
    'clues': clues.map((clue) => clue.toMap()).toList(),
    'candidateLocationIds': candidateLocationIds,
    'solutionLocationId': solutionLocationId,
    'supportingClueIds': supportingClueIds.toList(),
    'revealText': revealText,
    'wrongLocationHint': wrongLocationHint,
    'wrongCluesHint': wrongCluesHint,
    'solvedFlag': solvedFlag,
    'decorationItemId': decorationItemId,
  };

  factory MysteryConfig.fromMap(Map<String, dynamic> map) => MysteryConfig(
    question: map['question'] as String? ?? '',
    clues: [
      for (final raw in (map['clues'] as List? ?? const []))
        if (raw is Map<String, dynamic>) Clue.fromMap(raw),
    ],
    candidateLocationIds: [
      for (final id in (map['candidateLocationIds'] as List? ?? const []))
        if (id is String) id,
    ],
    solutionLocationId: map['solutionLocationId'] as String? ?? '',
    supportingClueIds: {
      for (final id in (map['supportingClueIds'] as List? ?? const []))
        if (id is String) id,
    },
    revealText: map['revealText'] as String? ?? '',
    wrongLocationHint: map['wrongLocationHint'] as String? ?? '',
    wrongCluesHint: map['wrongCluesHint'] as String? ?? '',
    solvedFlag: map['solvedFlag'] as String? ?? 'mystery_solved',
    decorationItemId: map['decorationItemId'] as String? ?? '',
  );
}

/// One place in the courtyard where something can be put.
class PreparationSlot {
  const PreparationSlot({
    required this.id,
    required this.label,
    required this.acceptedItemIds,
    required this.x,
    required this.y,
    this.filledText,
  });

  final String id;

  /// "By the doorway". Shown on the slot, so tap-to-place needs no explanation.
  final String label;

  final List<String> acceptedItemIds;
  final double x;
  final double y;

  /// What the scene says once something is here.
  final String? filledText;

  Map<String, dynamic> toMap() => {
    'id': id,
    'label': label,
    'acceptedItemIds': acceptedItemIds,
    'x': x,
    'y': y,
    if (filledText != null) 'filledText': filledText,
  };

  factory PreparationSlot.fromMap(Map<String, dynamic> map) => PreparationSlot(
    id: map['id'] as String? ?? '',
    label: map['label'] as String? ?? '',
    acceptedItemIds: [
      for (final id in (map['acceptedItemIds'] as List? ?? const []))
        if (id is String) id,
    ],
    x: (map['x'] as num?)?.toDouble() ?? 0.5,
    y: (map['y'] as num?)?.toDouble() ?? 0.5,
    filledText: map['filledText'] as String?,
  );
}

/// A look for the finished courtyard. Purely a matter of taste.
class DecorationStyle {
  const DecorationStyle({
    required this.id,
    required this.name,
    required this.description,
    required this.color,
    this.icon = Icons.auto_awesome_rounded,
  });

  final String id;
  final String name;
  final String description;
  final Color color;
  final IconData icon;

  Map<String, dynamic> toMap() => {
    'id': id,
    'name': name,
    'description': description,
    'color': color.toARGB32(),
    'icon': adventureIconName(icon),
  };

  factory DecorationStyle.fromMap(Map<String, dynamic> map) => DecorationStyle(
    id: map['id'] as String? ?? '',
    name: map['name'] as String? ?? '',
    description: map['description'] as String? ?? '',
    color: Color((map['color'] as num?)?.toInt() ?? 0xFF6A1B9A),
    icon: adventureIcon(map['icon'] as String?),
  );
}

/// Getting the courtyard ready.
class PreparationConfig {
  const PreparationConfig({
    required this.slots,
    required this.styles,
    required this.readyFlag,
  });

  final List<PreparationSlot> slots;

  /// **No style is ever wrong.** The brief is explicit and so is this comment:
  /// a cosmetic choice must not be marked incorrect. The slots have rules
  /// because a pot belongs on the fire; the colours do not.
  final List<DecorationStyle> styles;

  /// Set once every slot is filled.
  final String readyFlag;

  Map<String, dynamic> toMap() => {
    'readyFlag': readyFlag,
    'slots': slots.map((slot) => slot.toMap()).toList(),
    'styles': styles.map((style) => style.toMap()).toList(),
  };

  factory PreparationConfig.fromMap(Map<String, dynamic> map) =>
      PreparationConfig(
        readyFlag: map['readyFlag'] as String? ?? 'courtyard_ready',
        slots: [
          for (final raw in (map['slots'] as List? ?? const []))
            if (raw is Map<String, dynamic>) PreparationSlot.fromMap(raw),
        ],
        styles: [
          for (final raw in (map['styles'] as List? ?? const []))
            if (raw is Map<String, dynamic>) DecorationStyle.fromMap(raw),
        ],
      );
}

/// One way the adventure can finish.
class Ending {
  const Ending({
    required this.id,
    required this.title,
    required this.text,
    required this.celebration,
    this.requires = Requirement.none,
    this.color = const Color(0xFF00695C),
    this.icon = Icons.celebration_rounded,
  });

  final String id;
  final String title;

  /// What happened, in a paragraph.
  final String text;

  /// The single line the celebration scene shows.
  final String celebration;

  /// Endings are checked in order and the first match wins, so the more
  /// demanding one must come first. The last ending should always be reachable
  /// — the validator insists on it, otherwise a player could finish the
  /// adventure and be shown nothing.
  final Requirement requires;

  final Color color;
  final IconData icon;

  Map<String, dynamic> toMap() => {
    'id': id,
    'title': title,
    'text': text,
    'celebration': celebration,
    if (!requires.isAlwaysMet) 'requires': requires.toMap(),
    'color': color.toARGB32(),
    'icon': adventureIconName(icon),
  };

  factory Ending.fromMap(Map<String, dynamic> map) => Ending(
    id: map['id'] as String? ?? '',
    title: map['title'] as String? ?? '',
    text: map['text'] as String? ?? '',
    celebration: map['celebration'] as String? ?? '',
    requires: Requirement.fromMap(map['requires'] as Map<String, dynamic>?),
    color: Color((map['color'] as num?)?.toInt() ?? 0xFF00695C),
    icon: adventureIcon(map['icon'] as String?),
  );
}

/// One line of the quest journal.
class QuestStep {
  const QuestStep({
    required this.id,
    required this.title,
    required this.detail,
    required this.doneWhen,
    this.activeWhen = Requirement.none,
    this.hint,
  });

  final String id;
  final String title;

  /// What to do, in a sentence.
  final String detail;

  /// Status is DERIVED from the player's state rather than stored, so the
  /// journal can never drift out of step with the game. There is no way to
  /// mark a step done that did not actually happen.
  final Requirement doneWhen;

  final Requirement activeWhen;

  /// The optional nudge, shown only when the player asks for it.
  final String? hint;

  Map<String, dynamic> toMap() => {
    'id': id,
    'title': title,
    'detail': detail,
    'doneWhen': doneWhen.toMap(),
    if (!activeWhen.isAlwaysMet) 'activeWhen': activeWhen.toMap(),
    if (hint != null) 'hint': hint,
  };

  factory QuestStep.fromMap(Map<String, dynamic> map) => QuestStep(
    id: map['id'] as String? ?? '',
    title: map['title'] as String? ?? '',
    detail: map['detail'] as String? ?? '',
    doneWhen: Requirement.fromMap(map['doneWhen'] as Map<String, dynamic>?),
    activeWhen: Requirement.fromMap(map['activeWhen'] as Map<String, dynamic>?),
    hint: map['hint'] as String?,
  );
}

/// Where the cultural material in an adventure came from, and how far it has
/// been checked.
///
/// The same honesty rule as the cultural packs, for the same reason: a story
/// about somebody's festival that nobody from that place has read is a draft,
/// and the app says so on screen instead of presenting it as established.
class CulturalNote {
  const CulturalNote({
    required this.festival,
    required this.region,
    required this.summary,
    required this.references,
    this.reviewed = false,
  });

  final String festival;
  final String region;

  /// A few true sentences about the festival, from the curated reference pack.
  final String summary;

  final List<String> references;

  final bool reviewed;

  Map<String, dynamic> toMap() => {
    'festival': festival,
    'region': region,
    'summary': summary,
    'references': references,
    'reviewed': reviewed,
  };

  factory CulturalNote.fromMap(Map<String, dynamic> map) => CulturalNote(
    festival: map['festival'] as String? ?? '',
    region: map['region'] as String? ?? '',
    summary: map['summary'] as String? ?? '',
    references: [
      for (final value in (map['references'] as List? ?? const []))
        if (value is String) value,
    ],
    reviewed: map['reviewed'] as bool? ?? false,
  );
}

/// The complete adventure.
class Adventure {
  const Adventure({
    required this.id,
    required this.title,
    required this.intro,
    required this.objective,
    required this.startLocationId,
    required this.locations,
    required this.characters,
    required this.items,
    required this.market,
    required this.mystery,
    required this.preparation,
    required this.quests,
    required this.endings,
    required this.culturalNote,
    this.source = AdventureSource.bundled,
    this.createdAt,
  });

  final String id;
  final String title;

  /// The opening: who you are, where you are, and what is about to happen.
  final String intro;

  /// The one-line objective, always visible in the journal.
  final String objective;

  final String startLocationId;
  final List<AdventureLocation> locations;
  final List<AdventureCharacter> characters;
  final List<AdventureItem> items;
  final MarketConfig market;
  final MysteryConfig mystery;
  final PreparationConfig preparation;
  final List<QuestStep> quests;
  final List<Ending> endings;
  final CulturalNote culturalNote;
  final AdventureSource source;
  final DateTime? createdAt;

  AdventureLocation? location(String id) =>
      locations.where((place) => place.id == id).firstOrNull;

  AdventureCharacter? character(String id) =>
      characters.where((person) => person.id == id).firstOrNull;

  AdventureItem? item(String id) =>
      items.where((thing) => thing.id == id).firstOrNull;

  Clue? clue(String id) =>
      mystery.clues.where((clue) => clue.id == id).firstOrNull;

  Ending? ending(String id) =>
      endings.where((ending) => ending.id == id).firstOrNull;

  List<AdventureCharacter> charactersAt(String locationId) => [
    for (final person in characters)
      if (person.locationId == locationId) person,
  ];

  Adventure copyWith({String? id, AdventureSource? source, DateTime? createdAt}) =>
      Adventure(
        id: id ?? this.id,
        title: title,
        intro: intro,
        objective: objective,
        startLocationId: startLocationId,
        locations: locations,
        characters: characters,
        items: items,
        market: market,
        mystery: mystery,
        preparation: preparation,
        quests: quests,
        endings: endings,
        culturalNote: culturalNote,
        source: source ?? this.source,
        createdAt: createdAt ?? this.createdAt,
      );

  Map<String, dynamic> toMap() => {
    'id': id,
    'title': title,
    'intro': intro,
    'objective': objective,
    'startLocationId': startLocationId,
    'locations': locations.map((place) => place.toMap()).toList(),
    'characters': characters.map((person) => person.toMap()).toList(),
    'items': items.map((thing) => thing.toMap()).toList(),
    'market': market.toMap(),
    'mystery': mystery.toMap(),
    'preparation': preparation.toMap(),
    'quests': quests.map((quest) => quest.toMap()).toList(),
    'endings': endings.map((ending) => ending.toMap()).toList(),
    'culturalNote': culturalNote.toMap(),
    'source': source.name,
    if (createdAt != null) 'createdAt': createdAt!.toIso8601String(),
  };

  factory Adventure.fromMap(Map<String, dynamic> map) => Adventure(
    id: map['id'] as String? ?? '',
    title: map['title'] as String? ?? '',
    intro: map['intro'] as String? ?? '',
    objective: map['objective'] as String? ?? '',
    startLocationId: map['startLocationId'] as String? ?? '',
    locations: [
      for (final raw in (map['locations'] as List? ?? const []))
        if (raw is Map<String, dynamic>) AdventureLocation.fromMap(raw),
    ],
    characters: [
      for (final raw in (map['characters'] as List? ?? const []))
        if (raw is Map<String, dynamic>) AdventureCharacter.fromMap(raw),
    ],
    items: [
      for (final raw in (map['items'] as List? ?? const []))
        if (raw is Map<String, dynamic>) AdventureItem.fromMap(raw),
    ],
    market: MarketConfig.fromMap(
      map['market'] as Map<String, dynamic>? ?? const {},
    ),
    mystery: MysteryConfig.fromMap(
      map['mystery'] as Map<String, dynamic>? ?? const {},
    ),
    preparation: PreparationConfig.fromMap(
      map['preparation'] as Map<String, dynamic>? ?? const {},
    ),
    quests: [
      for (final raw in (map['quests'] as List? ?? const []))
        if (raw is Map<String, dynamic>) QuestStep.fromMap(raw),
    ],
    endings: [
      for (final raw in (map['endings'] as List? ?? const []))
        if (raw is Map<String, dynamic>) Ending.fromMap(raw),
    ],
    culturalNote: CulturalNote.fromMap(
      map['culturalNote'] as Map<String, dynamic>? ?? const {},
    ),
    source: AdventureSource.fromName(map['source'] as String?),
    createdAt: DateTime.tryParse(map['createdAt'] as String? ?? ''),
  );

  String toJson() => jsonEncode(toMap());

  factory Adventure.fromJson(String source) =>
      Adventure.fromMap(jsonDecode(source) as Map<String, dynamic>);
}
